import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SalesModal from "@/components/SalesModal";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Music Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className + " body"}>
        <div className="page-wrapper">
          
          <SalesModal />
          <Navbar />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
